version: "3"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqldb-data:/var/opt/mssql
    ports:
      - "${BACKEND_SQL_DATABASE_PORT}:1443"
    networks:
      - backend

  myshop.backend:
    image: myshop.backend
    build:
      context: ../src
      dockerfile: MyShop.Backend/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=MyShop;User Id=sa;Password=P@ssw0rd
      - ClientUrl:Swagger=http://${HOST_IP}:${BACKEND_PORT}
      - ClientUrl:Mvc=http://${HOST_IP}:${MVC_PORT}
      - ClientUrl:Blazor=http://${HOST_IP}:${BLAZOR_PORT}
      - ClientUrl:React=http://${HOST_IP}:${REACT_PORT}
      - ClientUrl:Angular=http://${HOST_IP}:${ANGULAR_PORT}
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - backend
      - frontend

  myshop.mvc:
    image: myshop.mvc
    build:
      context: ../src
      dockerfile: MyShop.Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings:BackendUrl=http://${HOST_IP}:${BACKEND_PORT}
    ports:
      - "${MVC_PORT}:80"
    networks:
      - frontend

  myshop.blazor:
    image: myshop.blazor
    build:
      context: ../src
      dockerfile: MyShop.BlazorFrontend/Dockerfile
    ports:
      - "${BLAZOR_PORT}:80"
    networks:
      - frontend

  myshop.react:
    image: myshop.react
    build:
      context: ../myshop-react
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://${HOST_IP}:${BACKEND_PORT}
    ports:
      - "${REACT_PORT}:80"
    networks:
      - frontend

  myshop.angular:
    image: myshop.angular
    build:
      context: ../myshop-angular
      dockerfile: Dockerfile
    ports:
      - "${ANGULAR_PORT}:80"
    networks:
      - frontend

volumes:
  sqldb-data:

networks:
  frontend:
  backend: