version: "3"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    volumes:
      - sqldb-data:/var/opt/mssql
    ports:
      - "${BACKEND_SQL_DATABASE_PORT}:1443"

  myshop.backend:
    image: myshop.backend
    build:
      context: ../src
      dockerfile: MyShop.Backend/Dockerfile
    depends_on:
      - sqldb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=sqldb,1433;Database=MyShop;User Id=sa;Password=P@ssw0rd
      - ClientUrl:Swagger=${HOST_URL}:${BACKEND_PORT}
      - ClientUrl:Mvc=${HOST_URL}:${MVC_PORT}
      - ClientUrl:Blazor=${HOST_URL}:${BLAZOR_PORT}
      - ClientUrl:React=${HOST_URL}:${REACT_PORT}
      - ClientUrl:Angular=${HOST_URL}:${ANGULAR_PORT}
    ports:
      - "${BACKEND_PORT}:80"

  myshop.mvc:
    image: myshop.mvc
    build:
      context: ../src
      dockerfile: MyShop.Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings:BackendUrl=${HOST_URL}:${BACKEND_PORT}
    ports:
      - "${MVC_PORT}:80"

  myshop.blazor:
    image: myshop.blazor
    build:
      context: ../src
      dockerfile: MyShop.BlazorFrontend/Dockerfile
    ports:
      - "${BLAZOR_PORT}:80"

  myshop.react:
    image: myshop.react
    build:
      context: ../myshop-react
      dockerfile: Dockerfile
    ports:
      - "${REACT_PORT}:80"

volumes:
  sqldb-data: